<?php
/**
 * Created by PhpStorm.
 * User: Red
 * Date: 2017/12/30
 * Time: 22:33
 */
class RedisFactory extends \yii\redis\ActiveRecord{
    public function loadModel($arr=[])
    {
        parent::attributes($arr); // TODO: Change the autogenerated stub
        parent::formName();
    }

}