<?php
namespace app\controllers;

use app\models\ModelFactory;
use app\models\VproAuthTable;
use Yii;
use yii\base\Model;
use yii\filters\auth\QueryParamAuth;
use yii\filters\VerbFilter;
use app\common\JwtAuth;

class AuthController extends BaseController {
    public $modelClass='app\models\Videoauth';
    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors['authenticator']=[
            'class'=>QueryParamAuth::className(),
            'tokenParam'=>'token',
            'except'=>['logout']
//            'optional'=>['logout']
        ];
        return $behaviors;
    }
    /**
     * 改写yii的action，将默认的index改成自定义的TokenAction
     * @return array
     */
    public function actions()
    {
        return [
            //index对应get，create对应post
            'create'=>[
                'class'=>'app\myactions\AuthAction',
                'modelClass'=>$this->modelClass
            ],
        ];
    }
    public function actionIndex(){
        return true;
    }
    public function actionLogout(){
        $request=Yii::$app->request;
        if($request->isGet){
            $auth_id=$request->get('id',false);
            if($auth_id){
                $auth=ModelFactory::loadModel("vpro_auth")->findOne(['auth_id'=>$auth_id]);
                $auth->auth_token="";
                if($auth->save()){
                    return ['status'=>'success'];
                }
            }
        }
        return ['statues'=>'failed'];
    }

}