<?php
/**
 * Created by PhpStorm.
 * User: szl4zsy
 * Date: 2/7/2017
 * Time: 3:03 PM
 */
namespace app\controllers;
use yii\rest\ActiveController;
use yii\web\Response;
use yii\filters\auth\QueryParamAuth;
use app\models\Blog;
use yii\filters\Cors;
use yii\helpers\ArrayHelper;

class InfoController extends ActiveController{
    public $modelClass='app\models\Blog';
    public function init()
    {
        parent::init();
        \Yii::$app->user->enableSession = false;
    }
    function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors['contentNegotiator']['formats']['text/html']=Response::FORMAT_JSON;
        $behaviors['authenticator'] = [
            'class' => QueryParamAuth::className(),
            'tokenParam'=>'token',
        ];
        $behaviors=ArrayHelper::merge($behaviors,[
            [
                'class'=>Cors::className(),
                'cors'=>[
                    'Origin' => ['http://localhost:8080'],//定义允许来源的数组
                    'Access-Control-Request-Method' => ['GET','POST','PUT','DELETE', 'HEAD', 'OPTIONS'],//允许动作的数组
                ],
                'actions' => [
                    'index' => [
                        'Access-Control-Allow-Credentials' => true,
                    ]
                ]
            ]
        ]);
        return $behaviors;
    }
    public function actions(){
        $actions=parent::actions();
        unset($actions['index']);
        return $actions;
    }

    public function actionIndex(){
        return Blog::find()->joinWith('blogMeta')->asArray()->all();
    }
}