<?php
/**
 * Created by PhpStorm.
 * User: szl4zsy
 * Date: 3/28/2017
 * Time: 3:53 PM
 */

namespace app\controllers;
use app\models\ModelFactory;
use Yii;
use app\models\VproVideoFiles;
use Qiniu\QiniuUtil;
use yii\base\Exception;
use yii\filters\auth\QueryParamAuth;

class ManageController extends BaseController
{
    public $modelClass='app\models\VproVideoFiles';
    public function behaviors()
    {
        //有了这个就需要get参数验证，验证方法定义在web.php中，identityClass, findIdentityByAccessToken验证token是否存在
        $behaviors=parent::behaviors(); // TODO: Change the autogenerated stub
//        $behaviors['authenticator']=[
//            'class'=>QueryParamAuth::className(),
//            'tokenParam'=>'token'
//        ];
        return $behaviors;
    }
    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        unset(
            $actions['index'],
            $actions['create'],
            $actions['delete']
    );
        return $actions;
    }
    public function actionIndex(){
        $util=new QiniuUtil();
        return $util->getVideoFiles();
//        $videoFiles=new VproVideoFiles();
//        return $videoList::find()->joinWith(['videosImg','videosFiles'])->asArray()->all();
//        return $videoFiles::find()->where(['v_userid'=>Videoauth::$current_user_id])->joinWith(['videosImg','videosFiles'])->asArray()->all();
    }
    public function actionDelete(){

    }
    public function actionCreate(){
        $request=Yii::$app->request;
        $postData=$request->getBodyParams();
        if($postData['action']=='delete' && isset($postData['key'])){
            $res=[];
            $util=new QiniuUtil();
            foreach($postData['key'] as $key => $value){
                $res[$value]=$util->deleteFile($value);
            }
            return $res;
        }
    }

}