<?php
/**
 * Created by PhpStorm.
 * User: SZL4ZSY
 * Date: 3/15/2017
 * Time: 11:03 AM
 */
namespace app\controllers;
use common\RedisData;
//class NavbarController extends ActiveController
class NavbarController extends BaseController
{
    public $modelClass = 'app\models\Navbar';
    public $res;
    function actions()
    {
        $redis=new RedisData();
        $this->res=$redis->getAll('navbar');
        if($this->res){
            $actions=parent::actions();
            unset($actions['index']);
            return $actions;
        }else{
            return parent::actions(); // TODO: Change the autogenerated stub
        }
    }
    function actionIndex(){
        return $this->res;
    }
}