<?php
/**
 * Created by PhpStorm.
 * User: SZL4ZSY
 * Date: 3/15/2017
 * Time: 11:03 AM
 */
namespace app\controllers;
use app\models\ModelFactory;
use app\models\Videosuser;
use Yii;
use yii\base\Exception;

class VideosuserController extends BaseController
{
    public $modelClass = 'app\models\Videosuser';
    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['index'],$actions['create']);
        //对应post动作，如果对该页面进行了post操作则会进入authAction.
        $actions['create']=[
             'class'=>'app\myactions\AuthAction',
             'modelClass'=>$this->modelClass
         ];
        return $actions;
    }
    public function actionIndex(){
        $request=Yii::$app->request;
        if($request->isGet){
            $id=$request->get('id',0);
            if($id>0){
                $videosUser=new Videosuser();
                return $videosUser::find()->where(['user_id'=>$id])->one();
            }else{
                return new class (){
                    function __construct()
                    {
                        $this->error='please transfer the user information!';
                    }
                };
            }
        }
    }
    public function actionAddinfo(){
        $request=Yii::$app->request;
        if($request->isPost){
            try{
                $videoUser=new Videosuser();
                $info=$request->post('key');
                if(isset($info['user_id'])){
                    $videoUser=$videoUser->find()->where(['user_id'=>$info['user_id']])->one();
                }
                foreach($info as $key => $value){
                    if($key!='user_id'){
                        $videoUser->$key=$value;
                    }
                }
                if($videoUser->save()){
                    $res=new \stdclass();
                    $res->status=true;
                    $res->user_id=$videoUser->user_id;
                    return $res;
                }
            }catch(Exception $e){
                $res=new \stdclass();
                $res->status=false;
                $res->message=$e->getMessage();
                return $res;
            }
        }
    }
}