<?php
/**
 * Created by PhpStorm.
 * User: SZL4ZSY
 * Date: 3/15/2018
 * Time: 3:00 PM
 */
namespace api\controllers;

use app\common\JwtAuth;
use app\controllers\BaseController;
use app\models\ModelFactory;

class AuthController extends BaseController
{
    public $modelClass = 'api\models\VproAuth';

    function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => JwtAuth::className(),
            /*
             *因为此post请求的 content-type不是one of the “application/x-www-form-urlencoded, multipart/form-data, or text/plain”, 所以Preflighted requests被发起。
             * “preflighted” requests first send an HTTP OPTIONS request header to the resource on the other domain, in order to determine whether the actual request is safe to send.
             * 然后得到服务器response许可之后，再发起其post请求。
             */
            'except' => ['create', 'options', 'user-list']
        ];
        return $behaviors;
    }

    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['index'], $actions['create']);
        $actions['create'] = [
            'class' => 'api\myactions\AuthAction',
            'modelClass' => $this->modelClass
        ];
        return $actions;
    }
    public function actionIndex()
    {
        return [];
    }

}