<?php
namespace api\controllers;

use app\controllers\CombaseController;
use app\models\ModelFactory;
use app\models\VproOrderLogs;
use Payment\Client\Charge;
use Payment\Common\PayException;
use Payment\Config;

use app\controllers\BaseController;

/**
 * Created by PhpStorm.
 * User: SZL4ZSY
 * Date: 1/29/2018
 * Time: 3:27 PM
 */

class PayController extends CombaseController {

    const PAY_WAIT=0;

    const PAY_SUCCESS=1;

    const PAY_DIFF_AMOUNT=2;

    function init()
    {
        $init = parent::init(); // TODO: Change the autogenerated stub

        return $init;
    }

    function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        return $behaviors;
    }
    function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        return $actions;
    }
    function actionPutWebPay($orderInfo) {
        $orderInfo = (array)json_decode($orderInfo);
        $orderInfo = array_map(function($v){
            return (string)$v;
        }, $orderInfo);
        /*$orderInfo=[
            'body'    => 'ali web pay',
            'subject'    => '测试支付宝',
            'order_no'    => '12345678912345678213',
            'timeout_express' => time() + 600,// 表示必须  内付款
            'amount'    => '0.01',// 单位为元 ,最小为0.01
            'return_param' => '123123',
            // 'client_ip' => isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : '127.0.0.1',// 客户地址
            'goods_type' => '1',// 0—虚拟类商品，1—实物类商品
//            'store_id' => '',
            // 说明地址：https://doc.open.alipay.com/doc2/detail.htm?treeId=270&articleId=105901&docType=1
            // 建议什么也不填
//            'qr_mod' => '',
        ];*/
        try{
            $orderInfo['amount'] = $orderInfo['amount'] > 0 ? (string)$orderInfo['amount'] : (string)1.5;
            $url = Charge::run(Config::ALI_CHANNEL_WEB,\Yii::$app->params['aliconfig'], $orderInfo);
            return $url;
        }catch(PayException $e){
            throw $e;
        }
    }

    function actionPaycallback() {
        $request = \Yii::$app->request;
        $res = $request->get();
        $log['total'] = $res['total_amount'];
        $log['order_id'] = $res['out_trade_no'];
        $log['trade_no'] = $res['trade_no'];
        $log['timestamp'] = $res['timestamp'];
        $log['auth_app_id'] = $res['auth_app_id'];
        $log['seller_id'] = $res['seller_id'];
        $log['app_id'] = $res['app_id'];
        $vproOrderLogs = new VproOrderLogs();
        // 验签失败
        if (
            $res['auth_app_id'] != \Yii::$app->params['aliconfig']['app_id'] ||
            $res['seller_id'] != \Yii::$app->params['aliconfig']['partner'] ||
            $res['app_id'] != \Yii::$app->params['aliconfig']['app_id']
        ) {
            //false
            $vproOrderLogs->log_operation = $this->params['PAY_ACCOUNT_INFO_MISMATCH'];
            $vproOrderLogs->log_time = time();
            $vproOrderLogs->log_message = json_encode($log);
            $vproOrderLogs->order_id = $log['order_id'];
            $vproOrderLogs->save();
            exit();
        }
        $vpro_order = ModelFactory::loadModel('vpro_order');
        $order_instance = $vpro_order::findOne(['order_id' => $res['out_trade_no']]);
        // 找到订单，更改状态
        if($order_instance !== null) {
            $order_instance->order_payment_id = $res['trade_no'];
            $order_instance->order_payment_price = $res['total_amount'];
        } else {
            // 没找到订单，订单不存在
            $vproOrderLogs->log_operation = $this->params['ORDER_NOT_EXIST'];
            $vproOrderLogs->log_time = time();
            $vproOrderLogs->log_message = json_encode($log);
            $vproOrderLogs->order_id = $log['order_id'];
            $vproOrderLogs->save();
            exit();
        }
        /**
         * payment:
         * 0:等待付款
         * 1：支付成功
         * 2：支付异常（如实收金额与订单数字不符）
         * 3：
         */
        if($order_instance->order_price !== $res['total_amount']) {
            $order_instance->order_payment = self::PAY_DIFF_AMOUNT;
        }
        $order_instance->order_payment = self::PAY_SUCCESS;

        $order_instance->save();

        $vproOrderLogs->log_operation = $this->params['PAY_SUCCESS'];
        $vproOrderLogs->log_message = json_encode($log);
        $vproOrderLogs->order_id = $log['order_id'];
        $vproOrderLogs->save();
        exit();
    }
}