<?php
namespace api\controllers;

use app\controllers\CombaseController;
use app\models\ModelFactory;
use Payment\Client\Charge;
use Payment\Common\PayException;
use Payment\Config;

use app\controllers\BaseController;

/**
 * Created by PhpStorm.
 * User: SZL4ZSY
 * Date: 1/29/2018
 * Time: 3:27 PM
 */

class PayController extends CombaseController {
//    public $modelClass='app\models\VproOrder';

    const PAY_WAIT=0;

    const PAY_SUCCESS=1;

    const PAY_DIFF_AMOUNT=2;

    function init()
    {
        $init = parent::init(); // TODO: Change the autogenerated stub

        return $init;
    }

    function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        return $behaviors;
    }
    function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        return $actions;
    }
    function actionPutWebPay() {
//        $orderInfo = (array)json_decode($orderInfo);
//        $orderInfo = array_map(function($v){
//            return (string)$v;
//        }, $orderInfo);
        $orderInfo=[
            'body'    => 'ali web pay',
            'subject'    => '测试支付宝',
            'order_no'    => '12345678912345678213',
            'timeout_express' => time() + 600,// 表示必须  内付款
            'amount'    => '0.01',// 单位为元 ,最小为0.01
            'return_param' => '123123',
            // 'client_ip' => isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : '127.0.0.1',// 客户地址
            'goods_type' => '1',// 0—虚拟类商品，1—实物类商品
//            'store_id' => '',
            // 说明地址：https://doc.open.alipay.com/doc2/detail.htm?treeId=270&articleId=105901&docType=1
            // 建议什么也不填
//            'qr_mod' => '',
        ];
//        var_export(\Yii::$app->getModule('api')->params['aliconfig']);
        try{
//            var_export($orderInfo);
//            exit();
            $orderInfo['amount'] = (string)1.5;
            $url = Charge::run(Config::ALI_CHANNEL_WEB,\Yii::$app->getModule('api')->params['aliconfig'], $orderInfo);
            return $url;
//            header('Location:' . $url);
        }catch(PayException $e){
            throw $e;
        }
    }

    function actionPaycallback(){
        $request = \Yii::$app->request;
        $res['order_id'] = $request->get('out_trade_no',false);
        $res['order_payment_id'] = $request->get('out_trade_no', false);
        $res['total_amount'] = $request->get('total_amount', false);
        $res['seller_id'] = $request->get('seller_id', false);

        $res['auth_app_id'] = $request->get('auth_app_id', false);
        if(
            $res['auth_app_id'] != \Yii::$app->getModule('api')->params['aliconfig']['app_id'] ||
            $res['seller_id']!=\Yii::$app->getModule('api')->params['aliconfig']['seller_id']){
            //false
        }
        $vpro_order=ModelFactory::loadModel('vpro_order');
        $order_instance = $vpro_order::findOne(['order_id'=>$res['order_id']]);
        if($order_instance === null){
            //false
        }
        /**
         * payment:
         * 0:等待付款
         * 1：支付成功
         * 2：支付异常（如实收金额与订单数字不符）
         * 3：
         */
        if($order_instance->order_price != $res['total_amount']){
            $order_instance->order_payment = self::PAY_DIFF_AMOUNT;
        }
        $order_instance->order_payment = self::PAY_SUCCESS;

        //order_log
    }
}