<?php
/**
 * Created by PhpStorm.
 * User: Red
 * Date: 2018/2/9
 * Time: 22:00
 */

namespace Services;

class Cart extends Services{
    function init()
    {
        $init = parent::init(); // TODO: Change the autogenerated stub

        return $init;
    }

}